### PR TITLE
Adding a tree walker example

### PR DESCRIPTION
**Pull request by albfan**
I know "src/main.rs" is not the right place to put this code, but as rust newbie, I'm looking for a friend:

- I use RUST_TREE_SITTER_TEST=true and fech the fixtures to have the tree-sitter-rust parser avaliable
   - how to add all other parsers?

- This code walks correctly in a rust source code, how to add this a a different repo with cargo
   - use this repo as a module or crate (I cannot install it with cargo install)
   - Colorize output with a crate
   - Maybe reproduce this walker with node cli?
   - Add options to select other parser, and provide source_code to parse from command line

Output from `cargo run`

```
source: fn test() {}
AST: (source_file (function_item (identifier) (parameters) (block)))
- node: (source_file (function_item (identifier) (parameters) (block)))
  kind: source_file
  start: 0, 0
  end: 0, 12
  content: fn test() {}
  - node: (function_item (identifier) (parameters) (block))
    kind: function_item
    start: 0, 0
    end: 0, 12
    content: fn test() {}
    - node: (fn)
      kind: fn
      start: 0, 0
      end: 0, 2
      content: fn
    - node: (identifier)
      kind: identifier
      start: 0, 3
      end: 0, 7
      content: test
    - node: (parameters)
      kind: parameters
      start: 0, 7
      end: 0, 9
      content: ()
      - node: (()
        kind: (
        start: 0, 7
        end: 0, 8
        content: (
      - node: ())
        kind: )
        start: 0, 8
        end: 0, 9
        content: )
    - node: (block)
      kind: block
      start: 0, 10
      end: 0, 12
      content: {}
      - node: ({)
        kind: {
        start: 0, 10
        end: 0, 11
        content: {
      - node: (})
        kind: }
        start: 0, 11
        end: 0, 12
        content: }
```

### CODE REVIEW

**Comment by albfan** [comment]
I've added arguments to main.rs So now you can do:

```
$ cargo run 'int main(char** args, int argc) { println("Hello world!");}' c

source: int main(char** args, int argc) { println("Hello world!");}
AST: (translation_unit (function_definition (primitive_type) (function_declarator (identifier) (parameter_list (parameter_declaration (primitive_type) (pointer_declarator (pointer_declarator (identifier)))) (parameter_declaration (primitive_type) (identifier)))) (compound_statement (expression_statement (call_expression (identifier) (argument_list (string_literal)))))))
- node: (translation_unit (function_definition (primitive_type) (function_declarator (identifier) (parameter_list (parameter_declaration (primitive_type) (pointer_declarator (pointer_declarator (identifier)))) (parameter_declaration (primitive_type) (identifier)))) (compound_statement (expression_statement (call_expression (identifier) (argument_list (string_literal)))))))
  kind: translation_unit
  start: 0, 0
  end: 0, 59
  content: int main(char** args, int argc) { println("Hello world!");}
  - node: (function_definition (primitive_type) (function_declarator (identifier) (parameter_list (parameter_declaration (primitive_type) (pointer_declarator (pointer_declarator (identifier)))) (parameter_declaration (primitive_type) (identifier)))) (compound_statement (expression_statement (call_expression (identifier) (argument_list (string_literal))))))
    kind: function_definition
    start: 0, 0
    end: 0, 59
    content: int main(char** args, int argc) { println("Hello world!");}
    - node: (primitive_type)
      kind: primitive_type
      start: 0, 0
      end: 0, 3
      content: int
    - node: (function_declarator (identifier) (parameter_list (parameter_declaration (primitive_type) (pointer_declarator (pointer_declarator (identifier)))) (parameter_declaration (primitive_type) (identifier))))
      kind: function_declarator
      start: 0, 4
      end: 0, 31
      content: main(char** args, int argc)
      - node: (identifier)
        kind: identifier
        start: 0, 4
        end: 0, 8
        content: main
      - node: (parameter_list (parameter_declaration (primitive_type) (pointer_declarator (pointer_declarator (identifier)))) (parameter_declaration (primitive_type) (identifier)))
        kind: parameter_list
        start: 0, 8
        end: 0, 31
        content: (char** args, int argc)
        - node: (()
          kind: (
          start: 0, 8
          end: 0, 9
          content: (
        - node: (parameter_declaration (primitive_type) (pointer_declarator (pointer_declarator (identifier))))
          kind: parameter_declaration
          start: 0, 9
          end: 0, 20
          content: char** args
          - node: (primitive_type)
            kind: primitive_type
            start: 0, 9
            end: 0, 13
            content: char
          - node: (pointer_declarator (pointer_declarator (identifier)))
            kind: pointer_declarator
            start: 0, 13
            end: 0, 20
            content: ** args
            - node: (*)
              kind: *
              start: 0, 13
              end: 0, 14
              content: *
            - node: (pointer_declarator (identifier))
              kind: pointer_declarator
              start: 0, 14
              end: 0, 20
              content: * args
              - node: (*)
                kind: *
                start: 0, 14
                end: 0, 15
                content: *
              - node: (identifier)
                kind: identifier
                start: 0, 16
                end: 0, 20
                content: args
        - node: (,)
          kind: ,
          start: 0, 20
          end: 0, 21
          content: ,
        - node: (parameter_declaration (primitive_type) (identifier))
          kind: parameter_declaration
          start: 0, 22
          end: 0, 30
          content: int argc
          - node: (primitive_type)
            kind: primitive_type
            start: 0, 22
            end: 0, 25
            content: int
          - node: (identifier)
            kind: identifier
            start: 0, 26
            end: 0, 30
            content: argc
        - node: ())
          kind: )
          start: 0, 30
          end: 0, 31
          content: )
    - node: (compound_statement (expression_statement (call_expression (identifier) (argument_list (string_literal)))))
      kind: compound_statement
      start: 0, 32
      end: 0, 59
      content: { println("Hello world!");}
      - node: ({)
        kind: {
        start: 0, 32
        end: 0, 33
        content: {
      - node: (expression_statement (call_expression (identifier) (argument_list (string_literal))))
        kind: expression_statement
        start: 0, 34
        end: 0, 58
        content: println("Hello world!");
        - node: (call_expression (identifier) (argument_list (string_literal)))
          kind: call_expression
          start: 0, 34
          end: 0, 57
          content: println("Hello world!")
        - node: (;)
          kind: ;
          start: 0, 57
          end: 0, 58
          content: ;
      - node: (})
        kind: }
        start: 0, 58
        end: 0, 59
        content: }
```

I didn't fix how to build parsers write in cplus (scanner.cc) so all that code is commented

**Comment by maxbrunsfeld** [comment]
:wave: Hey @albfan 

> as rust newbie, I'm looking for a friend

Welcome! I'm somewhat of a rust newbie myself, but I love the language so far. Glad you found this project interesting.

> I know `src/main.rs` is not the right place to put this code

Yeah, this repository is just intended as a library that other applications can build upon, not necessarily as its own program. I normally wouldn't include any actual parsers at all, except I just use `tree-sitter-rust` for the test suite.

I do have an experimental project, [tree-tags](https://github.com/maxbrunsfeld/tree-tags) that is a CLI program that uses this library and walks syntax trees to index function calls. It's not really ready for public consumption yet though.

**Comment by albfan** [comment]
tree-tags look fine. I would add a submodule in vendor dir for

https://github.com/maxbrunsfeld/tree-tags/blob/master/Cargo.toml#L19

See how I'm doing it on vala-tree-sitter https://gitlab.gnome.org/albfan/vala-tree-sitter/blob/c/.gitmodules

Btw, I'm ok with add vala-tree-sitter here (and maybe tree-sitter-vala parser too) if you want. If you're not aware this is vala: https://wiki.gnome.org/Projects/Vala

I do contributions on GNOME Builder https://gitlab.gnome.org/GNOME/gnome-builder/ and currently I'm exploring code folding https://gitlab.gnome.org/albfan/gtk-code-folding-vala. I want to use tree-sitter for AST folding strategy https://gitlab.gnome.org/albfan/gtk-code-folding-vala/issues/4, but possibilities are endless if we manage to deal with tree-sitter (refactor, highlight, indexing, navigating)

Will close this as tree-tags is a good guide, but would be great to add projects using tree-sitter somewhere in a wiki or documentation

**Comment by albfan** [comment]
So I finally made it as:

https://github.com/albfan/rust-tree-sitter-ast-viewer

I added all parsers into submodules, so `cargo build` checkout them:

https://github.com/albfan/rust-tree-sitter/tree/parsers

https://github.com/albfan/rust-tree-sitter-ast-viewer/blob/master/Cargo.toml#L7

I can't see other way to do it. How is it supposed that rust-tree-sitter will provide all parser implementations? If this is not resolved yet I can open a new issue

**Comment by maxbrunsfeld** [comment]
> How is it supposed that rust-tree-sitter will provide all parser implementations?

It's not expected. Right now, your application must build the parsers in its `build.rs` script. I might add a build script helper function to `rust-tree-sitter` that makes this process easier though.

**Comment by albfan** [comment]
> It's not expected. Right now, your application must build the parsers in its build.rs script. I might add a build script helper function to rust-tree-sitter that makes this process easier though.

Done on https://github.com/albfan/rust-tree-sitter-ast-viewer/commit/c78b9692af1cbfe0e60c9d3f1e75dd8c426822c0

Can I reuse libtree-sitter-runtime build on tree-sitter crate and only build parsers? is it worth it? About using rust-tree-sitter crate: Shouldn't be tags on repo?

NOTE: Promise this is the last forward message

**Comment by maxbrunsfeld** [comment]
Yeah, this crate takes care of building the tree-sitter runtime. If you use this crate, you don't need to build that. You just need to build the `parser.c` and optional `scanner.c`/`scanner.cc` file for each parser. Here's some example code that would go in your `build.rs`:

```rust
    let parser_names = [
        "tree-sitter-javascript",
        "tree-sitter-python",
        "tree-sitter-ruby",
    ];

    for parser_name in parser_names.iter() {
        let parser_dir_path: PathBuf = ["vendor", parser_name].iter().collect();
        let parser_src_path = parser_dir_path.join("src");
        let parser_c_path = parser_src_path.join("parser.c");
        let scanner_c_path = parser_src_path.join("scanner.c");
        let scanner_cc_path = parser_src_path.join("scanner.cc");

        println!("cargo:rerun-if-changed={}", parser_c_path.to_str().unwrap());
        cc::Build::new()
            .include(&parser_src_path)
            .opt_level(0)
            .file(&parser_c_path)
            .compile(&(String::from(*parser_name) + "_parser"));
        if scanner_cc_path.exists() {
            println!("cargo:rerun-if-changed={}", scanner_cc_path.to_str().unwrap());
            cc::Build::new()
                .cpp(true)
                .flag_if_supported("-Wno-unused-parameter")
                .include(&parser_src_path)
                .file(&scanner_cc_path)
                .compile(&(String::from(*parser_name) + "_scanner"));
        } else if scanner_c_path.exists() {
            println!("cargo:rerun-if-changed={}", scanner_c_path.to_str().unwrap());
            cc::Build::new()
                .flag_if_supported("-Wno-unused-parameter")
                .include(&parser_src_path)
                .file(&scanner_c_path)
                .compile(&(String::from(*parser_name) + "_scanner"));
        }
    }
```

In the future, I might encapsulate some of this into a helper function in this crate.

**Comment by albfan** [comment]
Ok, so it will read all the libs there, ok. I see it, thanks

**Pull request closed without merging**
